apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hoan.ln91@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        cloudflare:
          email: tuananh.qaa@gmail.com
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
    # - http01:
    #     ingress:
    #       class: nginx
